version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: memorymaster
      POSTGRES_PASSWORD: memorymaster
      POSTGRES_DB: MemoryMaster-Backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "memorymaster", "-d", "MemoryMaster-Backend"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  memorymaster-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memorymaster_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://memorymaster:memorymaster@postgres:5432/MemoryMaster-Backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
